name: Update Playo data and Publish Site

# Controls when the action will run.
on:
  # Add run this workflow button to GH
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
        cache: 'pip'
    - run: pip install -r requirements.txt
    - env:
        PLAYO_AUTH: ${{ secrets.PLAYO_AUTH }}
      run: scripts/fetch_venues.py all
    - env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: scripts/gh-actions-update-venues.sh
